sudo: required
dist: trusty
addons:
  firefox: latest
  chrome: stable
language: python
python:
- '2.7'
- '3.5'
- '3.6'

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

install:
- pip install pipenv twine

script:
- pipenv install --dev
- pipenv run py.test -sv --cov-config .coveragerc --cov-report html:skip-covered --cov-report
  term:skip-covered --cov=webdriver_manager --tb=short tests/
- codecov
- python setup.py bdist_wheel
- twine upload --repository-url https://test.pypi.org/legacy/ dist/*
- twine upload dist/*

after_script:
- "./.upload_reports.sh"

notifications:
  email:
    recipients:
    - sergio_89@ukr.net